services:
  - type: web
    name: proship-dashboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PROSHIP_USERNAME
        sync: false
      - key: PROSHIP_PASSWORD
        sync: false
